# /etc/nginx/nginx.conf или /etc/nginx/sites-available/api-gateway

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;
}

# eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJib2IifQ.hiMVLmssoTsy1MqbmIoviDeFPvo-nCd92d4UFiN2O2I