---
- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: LIGHTHOUSE | Install git
      become: true
      ansible.builtin.package:
        name: git
        state: present
  roles:
    - name: lighthouse
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - name: clickhouse
- name: Install Clickhouse
  hosts: vector
  roles:
    - name: vector
